# Generated by Django 5.2.1 on 2025-05-27 01:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doador',
            options={'ordering': ['nome'], 'verbose_name': 'doador', 'verbose_name_plural': 'doadores'},
        ),
        migrations.AlterModelOptions(
            name='recebedor',
            options={'ordering': ['nome'], 'verbose_name': 'recebedor', 'verbose_name_plural': 'recebedores'},
        ),
        migrations.AddField(
            model_name='doador',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='data de cadastro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doador',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, verbose_name='endereço'),
        ),
        migrations.AddField(
            model_name='doador',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='observações'),
        ),
        migrations.AddField(
            model_name='doador',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='última atualização'),
        ),
        migrations.AddField(
            model_name='recebedor',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='data de cadastro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recebedor',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, verbose_name='endereço'),
        ),
        migrations.AddField(
            model_name='recebedor',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='observações'),
        ),
        migrations.AddField(
            model_name='recebedor',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='última atualização'),
        ),
        migrations.AlterField(
            model_name='doador',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='doador',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='doador',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='telefone'),
        ),
        migrations.AlterField(
            model_name='recebedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='recebedor',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='recebedor',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='telefone'),
        ),
    ]
