# Generated by Django 5.2.1 on 2025-05-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0002_alter_doador_options_alter_recebedor_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='doador',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False), ('telefone__isnull', False)), fields=('email', 'telefone'), name='unique_doador_email_telefone'),
        ),
        migrations.AddConstraint(
            model_name='doador',
            constraint=models.UniqueConstraint(condition=models.Q(('endereco__isnull', False)), fields=('nome', 'endereco'), name='unique_doador_nome_endereco'),
        ),
        migrations.AddConstraint(
            model_name='recebedor',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False), ('telefone__isnull', False)), fields=('email', 'telefone'), name='unique_recebedor_email_telefone'),
        ),
        migrations.AddConstraint(
            model_name='recebedor',
            constraint=models.UniqueConstraint(condition=models.Q(('endereco__isnull', False)), fields=('nome', 'endereco'), name='unique_recebedor_nome_endereco'),
        ),
    ]
