# Generated by Django 5.2.1 on 2025-05-27 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0003_doador_unique_doador_email_telefone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['nome'], 'verbose_name': 'item', 'verbose_name_plural': 'itens'},
        ),
        migrations.AlterField(
            model_name='item',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='item',
            name='disponivel',
            field=models.BooleanField(default=True, verbose_name='disponível'),
        ),
        migrations.AlterField(
            model_name='item',
            name='doador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='doacoes.doador', verbose_name='doador'),
        ),
        migrations.AlterField(
            model_name='item',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='itens/', verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='item',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tipo',
            field=models.CharField(choices=[('RO', 'Roupas'), ('MO', 'Móveis'), ('CO', 'Comidas'), ('PE', 'Perecíveis'), ('EL', 'Eletrônicos'), ('LI', 'Livros'), ('BR', 'Brinquedos'), ('UD', 'Utensílios Domésticos'), ('MS', 'Material Escolar'), ('FE', 'Ferramentas'), ('JR', 'Jornais/Revistas'), ('CB', 'Cobertores'), ('CA', 'Calçados'), ('AC', 'Acessórios'), ('IM', 'Instrumentos Musicais'), ('PH', 'Produtos de Higiene'), ('ME', 'Medicamentos'), ('VE', 'Veículos'), ('ED', 'Eletrodomésticos'), ('MC', 'Materiais de Construção'), ('OU', 'Outros')], max_length=2, verbose_name='tipo'),
        ),
    ]
