# Generated by Django 5.2.1 on 2025-05-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0004_alter_item_options_alter_item_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doador',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='doador',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='doador',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='telefone'),
        ),
        migrations.AlterField(
            model_name='recebedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='recebedor',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='recebedor',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='telefone'),
        ),
    ]
