# Generated by Django 5.2.1 on 2025-05-28 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0005_alter_doador_email_alter_doador_endereco_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doacao',
            options={'ordering': ['-data'], 'verbose_name': 'doação', 'verbose_name_plural': 'doações'},
        ),
        migrations.RemoveConstraint(
            model_name='doador',
            name='unique_doador_email_telefone',
        ),
        migrations.RemoveConstraint(
            model_name='doador',
            name='unique_doador_nome_endereco',
        ),
        migrations.RemoveConstraint(
            model_name='recebedor',
            name='unique_recebedor_email_telefone',
        ),
        migrations.RemoveConstraint(
            model_name='recebedor',
            name='unique_recebedor_nome_endereco',
        ),
        migrations.AddField(
            model_name='doacao',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='observações'),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data da doação'),
        ),
    ]
